<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ExpedienteImplService" targetNamespace="http://impl.consejo.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://impl.consejo.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://impl.consejo.com/" schemaLocation="expedienteimpl_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="crearExpediente">
    <wsdl:part name="parameters" element="tns:crearExpediente">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="crearExpedienteResponse">
    <wsdl:part name="parameters" element="tns:crearExpedienteResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ExpedienteImpl">
    <wsdl:operation name="crearExpediente">
      <wsdl:input name="crearExpediente" message="tns:crearExpediente">
    </wsdl:input>
      <wsdl:output name="crearExpedienteResponse" message="tns:crearExpedienteResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ExpedienteImplServiceSoapBinding" type="tns:ExpedienteImpl">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="crearExpediente">
      <soap:operation soapAction="urn:CrearExpediente" style="document"/>
      <wsdl:input name="crearExpediente">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="crearExpedienteResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ExpedienteImplService">
    <wsdl:port name="ExpedienteImplPort" binding="tns:ExpedienteImplServiceSoapBinding">
      <soap:address location="http://localhost:8080/Expediente/services/ExpedienteImplPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
